# Site settings
# title: Jekyll-Uno
title: JaeChan's dev blog
# description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
description: 'welcome'
# url: 'http://joshgerdes.com/jekyll-uno'
url: 'http://wocksl.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Yoon Jae Chan'
  email: wocksl1998@gmail.com
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  github_username:  wocksl
  # linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
